name: Automate PR with GH Action
on: [push]

jobs:
  automated-pr:
    name: Run automated PR
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create translation PR
        run: |
          git config user.name "${{ github.event.head_commit.author.name }}"
          git config user.email "${{ github.event.head_commit.author.email }}"

          git checkout -b feat/automated-pr-gh-action

          date > src/time.txt
          git add src/*.txt
          git commit -m 'ci: update time.txt via automated action [skip ci]' || "No commit changes"

          git push origin feat/automated-pr-gh-action
          gh pr create --title "ci: update time.txt via automated action [skip ci]" --body "" --base main

  date:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: save current date
        run: |
          # do some operation that changes a file in the git repo
          date > src/time.txt
          cat src/time.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use '${{ github.event.head_commit.author.name }}' with no email by default
          git config user.name "${{ github.event.head_commit.author.name }}"
          git config user.email "${{ github.event.head_commit.author.email }}"
          git branch --show-current

      - name: commit
        run: |
          # Stage the file, commit and push
          git checkout -b feat/pr-automation
          git add src/time.txt
          git commit -m "new date commit [skip ci]"
          git branch --show-current
          git push origin feat/pr-automation
